BUILDSCAD_PROJECT=osrsIconPixelModels
BUILDSCAD_VERSION=0.1.0
BUILDSCAD_AUTHOR=dduxx
BUILDSCAD_ASSEMBLIES=scad/assemblies/skills/skill_icon.scad[SKILL="agility"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="attack"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="construction"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="cooking"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="crafting"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="defence"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="farming"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="firemaking"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="fishing"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="fletching"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="herblore"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="hitpoints"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="hunter"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="magic"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="mining"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="prayer"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="ranged"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="runecraft"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="sailing"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="slayer"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="smithing"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="strength"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="thieving"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="woodcutting"],\
    scad/assemblies/skills/skill_icon.scad[SKILL="agility";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="attack";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="construction";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="cooking";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="crafting";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="defence";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="farming";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="firemaking";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="fishing";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="fletching";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="herblore";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="hitpoints";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="hunter";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="magic";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="mining";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="prayer";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="ranged";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="runecraft";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="sailing";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="slayer";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="smithing";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="strength";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="thieving";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="woodcutting";HAS_PLAQUE=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="agility";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="attack";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="construction";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="cooking";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="crafting";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="defence";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="farming";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="firemaking";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="fishing";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="fletching";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="herblore";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="hitpoints";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="hunter";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="magic";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="mining";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="prayer";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="ranged";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="runecraft";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="sailing";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="slayer";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="smithing";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="strength";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="thieving";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/skills/skill_icon.scad[SKILL="woodcutting";HAS_PLAQUE=true;HAS_MAX_LEVEL=true],\
    scad/assemblies/runes/rune_icon.scad[RUNE="aether"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="air"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="astral"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="blood"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="body"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="chaos"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="cosmic"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="death"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="dust"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="earth"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="fire"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="lava"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="law"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="mind"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="mist"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="mud"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="nature"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="smoke"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="soul"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="steam"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="sunfire"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="water"],\
    scad/assemblies/runes/rune_icon.scad[RUNE="wrath"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="10th_birthday_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="20th_anniversary_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="accumulator_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="achievement_diary_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="achievement_diary_cape_(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="agility_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="agility_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="ardougne_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="assembler_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="attack_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="attack_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="banana_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="cabbage_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="classic_imp_tail"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="cloak_of_ruin"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="clue_hunter_cloak"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="cobweb_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="construct._cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="construct._cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="cooking_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="cooking_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="crafting_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="crafting_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="defence_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="defence_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="farming_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="farming_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="firemaking_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="firemaking_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="fire_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="fishing_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="fishing_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="fletching_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="fletching_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="gnome_child_backpack"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="guthix_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="herblore_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="herblore_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="hitpoints_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="hitpoints_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="hunter_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="hunter_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="imbued_guthix_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="imbued_saradomin_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="imbued_zamorak_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="infernal_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="magic_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="magic_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="mining_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="mining_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="music_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="music_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="mythical_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="ornate_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="prayer_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="prayer_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="quest_point_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="quest_point_cape_(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="rainbow_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="ranging_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="ranging_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="runecraft_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="runecraft_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="sack_of_coal"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="sack_of_presents"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="sailing_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="sailing_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="saradomin_max_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="slayer_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="slayer_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="smithing_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="smithing_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="snow_imp_costume_tail"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="strength_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="strength_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="thieving_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="thieving_cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="witch_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="woodcut._cape(t)"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="woodcutting_cape"],\
    scad/assemblies/capes/cape_icon.scad[CAPE="zamorak_max_cape"]
BUILDSCAD_LOG_LEVEL=INFO
BUILDSCAD_OUTPUT_FORMAT=stl,png
BUILDSCAD_OPENSCAD_COLORSCHEME=DeepOcean
BUILDSCAD_IMAGESIZE=1280,720
BUILDSCAD_ENABLE_EXPERIMENTAL=true
BUILDSCAD_OPENSCAD_PATH=openscad-nightly
